name: Levitsky Studio
favicon: null
layout_spectrum: 0.04692083899863064
typography_spectrum: 0.16580276167951524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
